Add a port to IBM z/Architecture (s390x) running Linux -- Valgrind side components. (Florian Krohm <britzel@acm.org> and Christian Borntraeger <borntraeger@de.ibm.com>).  Fixes #243404.
git-svn-id: svn://svn.valgrind.org/valgrind/trunk@11604

diff --git a/exp-ptrcheck/tests/is_arch_supported b/exp-ptrcheck/tests/is_arch_supported
--- a/exp-ptrcheck/tests/is_arch_supported
+++ b/exp-ptrcheck/tests/is_arch_supported
@@ -1,7 +1,7 @@
 #!/bin/sh
 #
-# Not all architectures are supported by exp-ptr. Currently, PowerPC and ARM
-# are not supported and will fail these tests as follows:
+# Not all architectures are supported by exp-ptr. Currently, PowerPC, s390x
+# and ARM are not supported and will fail these tests as follows:
 # WARNING: exp-ptrcheck on <blah> platforms: stack and global array
 # WARNING: checking is not currently supported.  Only heap checking is
 # WARNING: supported.
@@ -10,6 +10,6 @@
 # architectures.
 
 case `uname -i` in
-  ppc*|arm*) exit 1;;
+  ppc*|arm*|s390x) exit 1;;
   *)         exit 0;;
 esac
